name: Publish

on:
  push:
    branches:
      - v1

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v5
    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: |
          8
          16
          17
          21

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5

    - name: Get version from gradle.properties
      run: |
        VERSION=$(grep "^version=" gradle.properties | cut -d'=' -f2)
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Get git hash
      run: echo "GIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Publish to maven repository
      env:
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
      run: ./gradlew publish -Pversion="${VERSION}-SNAPSHOT"

    - name: Build with Gradle
      run: ./gradlew clean build -Pversion="${VERSION}+${GIT_HASH}"

    - name: Upload to Registry
      uses: plasmoapp/actions/.github/actions/upload-to-registry@main
      with:
        registry_url: ${{ secrets.REGISTRY_URL }}
        upload_token: ${{ secrets.REGISTRY_UPLOAD_TOKEN }}
        files_glob: plugin/build/libs/*${{ env.GIT_HASH }}.jar
        message: ${{ github.event.head_commit.message }}

    - uses: actions/upload-artifact@v4
      with:
        name: pv-addon-discs
        path: |
          plugin/build/libs/*.jar
          !plugin/build/libs/*-@(sources).jar
