name: Publish Release

on:
  workflow_dispatch:
    inputs:
      release-type:
        description: 'Release type'
        required: true
        type: choice
        options:
          - release
          - beta
          - alpha

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: |
            8
            16
            17
            21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Build with Gradle
        run: ./gradlew build

      - name: Publish to Modrinth
        uses: apehum/mc-publish@master
        with:
          modrinth-id: WXJRlyZ9
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          modrinth-dependencies: |
            plasmo-voice
            pv-addon-lavaplayer-lib
            packetevents

          version-type: ${{ inputs.release-type }}

          changelog-file: changelog.md

          files: plugin/build/libs/*.jar

          loaders: |
            paper
            purpur
            folia
          game-versions: |
            1.16.5
            1.17.1
            1.18.2
            >=1.19.2

      - name: Publish to GitHub
        uses: Apehum/mc-publish@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-generate-changelog: false
          github-prerelease: ${{ inputs.release-type != 'release' }}
          changelog-file: changelog.md

          files: plugin/build/libs/*.jar
